// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/connect.ts";
import * as $1 from "./routes/api/create_game.ts";
import * as $2 from "./routes/api/join_game.ts";
import * as $3 from "./routes/host/[game].tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/player/[id].tsx";
import * as $6 from "./routes/player/join.tsx";
import * as $$0 from "./islands/CreateOrJoinGameButtons.tsx";
import * as $$1 from "./islands/Host.tsx";
import * as $$2 from "./islands/JoinGame.tsx";

const manifest = {
  routes: {
    "./routes/api/connect.ts": $0,
    "./routes/api/create_game.ts": $1,
    "./routes/api/join_game.ts": $2,
    "./routes/host/[game].tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/player/[id].tsx": $5,
    "./routes/player/join.tsx": $6,
  },
  islands: {
    "./islands/CreateOrJoinGameButtons.tsx": $$0,
    "./islands/Host.tsx": $$1,
    "./islands/JoinGame.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
